language: node_js
os: linux
dist: focal
node_js:
  - 18
  - 16
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN}
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_API_TOKEN
  edge: true
  cleanup: false
  on:
    tags: true
