language: node_js
os: linux
dist: focal
node_js:
  - 18
  - 16
cache:
  directories:
    - node_modules
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run test
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - chmod +x codecov
        - ./codecov -t ${CODECOV_TOKEN}
    - stage: deploy
      script:
        - npm run build
      node_js: 18
      deploy: &npm
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_API_TOKEN
        edge: true
        cleanup: false
        on:
          tags: true
